void test_ld_elf_unit(void);
void test_ld_elf_input(void);
void test_ld_elf_archive(void);
void test_ld_elf_script(void);
void test_ld_elf_crt(void);
void test_ld_elf_basic(void);
void test_ld_elf_layout(void);
void test_ld_elf_linker_defined(void);
void test_ld_elf_link_order(void);
void test_ld_elf_reloc(void);
void test_ld_elf_aarch64_got(void);
void test_ld_elf_riscv_uleb(void);
void test_ld_elf_rel_input(void);
void test_ld_elf_relax(void);
void test_ld_elf_unwind(void);
void test_ld_elf_ifunc(void);
void test_ld_elf_property(void);
void test_ld_elf_property_notes(void);
void test_ld_elf_relro(void);
void test_ld_elf_debug(void);
void test_ld_elf_debug_link(void);
void test_ld_elf_debug_merge(void);
void test_ld_elf_dynamic(void);
void test_ld_elf_pie(void);
void test_ld_elf_zlib(void);

void test_ld_elf(void) {
    test_ld_elf_unit();
    test_ld_elf_input();
    test_ld_elf_archive();
    test_ld_elf_script();
    test_ld_elf_crt();
    test_ld_elf_basic();
    test_ld_elf_layout();
    test_ld_elf_linker_defined();
    test_ld_elf_link_order();
    test_ld_elf_reloc();
    test_ld_elf_aarch64_got();
    test_ld_elf_riscv_uleb();
    test_ld_elf_rel_input();
    test_ld_elf_relax();
    test_ld_elf_unwind();
    test_ld_elf_ifunc();
    test_ld_elf_property();
    test_ld_elf_property_notes();
    test_ld_elf_relro();
    test_ld_elf_debug();
    test_ld_elf_debug_link();
    test_ld_elf_debug_merge();
    test_ld_elf_dynamic();
    test_ld_elf_pie();
    test_ld_elf_zlib();
}
