set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)

#set(CPACK_OUTPUT_FILE_PREFIX ${PROJECT_SOURCE_DIR}/releases)

set(CPACK_PACKAGE_FILE_NAME "nature-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_GENERATOR "TGZ")


message(STATUS "wille generators: ${CPACK_GENERATOR}")

include(CPack)